#SPDX-License-Identifier: MIT-0
---
# tasks file for role/jenkins
- name: Create Jenkins directory
  file:
    path: /opt/jenkins
    state: directory
    mode: 0755

- name: Copy docker-compose.yaml to Jenkins directory on the server
  copy:
    src: "docker-compose.yaml"
    dest: "/opt/jenkins/docker-compose.yaml"

- name: Start Jenkins container
  command: "docker compose up -d"
  args:
    chdir: /opt/jenkins

- name: Wait for Jenkins inital admin password to be generated
  wait_for:
    path: "{{ jenkins_initial_password }}"
    state: present
    timeout: 60
    

- name: Get Jenkins admin password file content
  command: "cat {{ jenkins_initial_password }}"
  register: jenkins_password
  changed_when: false

- name: Display Jenkins password
  debug:
    msg: "Jenkins server {{ ansible_host }} initial administrator password: {{ jenkins_password.stdout }}"
    