#SPDX-License-Identifier: MIT-0
---
# vars file for role/jenkins
jenkins_password_file_remote: /opt/jenkins_data/secrets/initialAdminPassword

jenkins_password_file_local: "{{ playbook_dir }}/../secrets/jenkins/jenkins_password"